[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[server]
headless = true

[pages]
order = ["main", "frame", "dpl_rel_new", "dpl_mtl_new"]
